// Core strings (page shell, HUD, scene labels, mass presets, chapter 1 and 6).
// Chapter and feature modules keep their own tables next to their code.

import { defineStrings, plural } from "./i18n.js";

const en = {
  // ---- page -------------------------------------------------------------------
  "page.title": "Lagrange Points",
  "page.question": "Where can a spacecraft ride along with Earth, engine off?",
  "page.canvas":
    "Sun, Earth and a movable probe. Arrows show the Sun's pull, Earth's pull and the spin push of the rotating frame, drawn tip to tail. Use the arrow keys to move the probe.",
  "page.noscript": "This explorer needs JavaScript to draw the scene.",
  "page.lang": "Русский",
  "page.langShort": "RU",
  "page.langAria": "Switch the site to Russian",

  // ---- HUD ----------------------------------------------------------------------
  "hud.tracker": "Balance points found",
  "hud.showAll": "Show all",
  "hud.help": "Help and keyboard shortcuts",
  "hud.menu": "Menu",
  "hud.legend": "Arrow legend",
  "hud.hold": "Hold: real motion",
  "hud.holdTitle": "Hold to watch the real motion, without the spinning view",
  "slot.found": "{name}: found. Jump there",
  "slot.shown": "{name}: shown. Jump there",
  "slot.hidden": "{name}: not found yet",
  "status.balanced": "Balanced",
  "status.leftover": "Leftover {pct}",

  // ---- arrows -------------------------------------------------------------------
  "leg.sun": "Sun pull",
  "leg.earth": "Earth pull",
  "leg.cf": "spin push",
  "leg.net": "leftover",
  "note.sun": "Sun pull: gravity toward the Sun. Four times weaker at twice the distance.",
  "note.earth": "Earth pull: gravity toward Earth. Same rule, but Earth is lighter.",
  "note.cf":
    "Spin push: the view spins with the Sun and Earth. Anything riding along gets flung straight away from the centre of mass (CM), harder the farther out it is. Dashed, like the line it copies.",
  "note.net":
    "Leftover: the three pulls added tip to tail. Where it vanishes, a probe can ride along with Earth, engine off.",

  // ---- scene --------------------------------------------------------------------
  "body.sun": "Sun",
  "body.earth": "Earth",
  "body.cm": "CM",
  "badge.scale": "arrows ×{k}",
  "badge.lanes": "lanes offset for clarity",
  "leftover.tiny": "< 0.01%",

  // ---- numbers card ---------------------------------------------------------------
  "numbers.title": "Numbers",
  "numbers.close": "Close numbers",
  "numbers.dSun": "Distance to Sun",
  "numbers.dEarth": "Distance to Earth",
  "numbers.dCm": "Distance to CM",
  "numbers.leftover": "Leftover",
  "numbers.nearest": "Nearest point",
  "numbers.hill": "Hill radius",
  "numbers.footReal": "Real Sun–Earth ratio: distances in km (1 a = 149.6 million km).",
  "numbers.foot": "a = Sun–Earth distance. Pulls as a share of all three pulls.",
  "unit.km": "{n} km",
  "unit.mkm": "{n} million km",

  // ---- dock ---------------------------------------------------------------------
  "dock.label": "Guide and mass",
  "dock.chapters": "Chapters",
  "dock.chapter": "Chapter: {title}",
  "dock.sweep": "Sweep the mass from tiny to equal and back",
  "dock.sweepTitle": "Sweep the mass (S)",
  "dock.stopSweep": "Stop the sweep",
  "dock.mass": "Earth mass, % of Sun",
  "mass.valuePreset": "{pct} of the Sun's mass, the {system} ratio",
  "mass.valueTag": "{pct} of the Sun's mass, {tag}",
  "tick.routhTitle": "Below about 4%, a probe at L4 or L5 stays nearby when nudged (Routh's limit)",
  "tick.routhAria": "Stability limit, 4 percent",
  "tick.presetTitle": "{system} mass ratio: {pct}",
  "tick.equalTitle": "Equal masses: {pct}",
  "tick.defaultTitle": "{pct}: this site's default, exaggerated so every effect is easy to see",
  "tick.presetAria": "{label}: {system} ratio",

  // ---- mass presets ---------------------------------------------------------------
  "preset.earth": "Earth",
  "preset.earthShort": "Earth",
  "preset.jupiter": "Jupiter",
  "preset.jupiterShort": "Jup",
  "preset.moon": "Moon",
  "preset.moonShort": "Moon",
  "preset.charon": "Charon",
  "preset.charonShort": "Charon",
  "system.earth": "Sun–Earth",
  "system.jupiter": "Sun–Jupiter",
  "system.moon": "Earth–Moon",
  "system.charon": "Pluto–Charon",
  "system.default": "this site's default",
  "system.equal": "equal masses",
  "tag.system": "{system} ratio",
  "tag.equal": "equal masses",
  "tag.lighter": "{x}× lighter than real Earth",
  "tag.real": "about real Earth",
  "tag.heavier": "{x}× real Earth",
  "num.million": "{n} million",

  // ---- chapters -------------------------------------------------------------------
  "chapter.find": "Find the balance",
  "chapter.triangle": "Why a triangle?",
  "chapter.line": "Three on the line",
  "chapter.real": "Real scale",
  "chapter.letgo": "Let go",
  "chapter.explore": "Explore",

  // ---- menu ---------------------------------------------------------------------
  "menu.layers": "Layers",
  "menu.numbers": "Numbers",
  "menu.real": "Hold: real motion",
  "menu.showAll": "Show all points",
  "menu.share": "Copy link to this view",
  "menu.reset": "Reset probe and mass",
  "menu.restart": "Start over",
  "menu.help": "Help and keys",
  "layer.labels": "Arrow labels",
  "layer.sight": "Lines to Sun, Earth, CM",
  "layer.magnifier": "Magnify tiny leftovers",
  "layer.compass": "Circles of radius a",
  "layer.shares": "Mass shares",
  "layer.profile": "Pull along the axis",
  "layer.fan": "Fan arrows (not chained)",
  "layer.locked": "Hidden during the hunt: it gives the answer away",
  "ui.fit": "Fit view",
  "ui.close": "Close",
  "toast.notFound": "Not found yet. Keep looking!",
  "toast.copied": "Link copied",
  "announce.notFound": "{name} is not found yet.",
  "confirm.restart": "Start over? The points you found will be forgotten.",

  // ---- screen reader ------------------------------------------------------------------
  "sr.balanced": "Balanced at {name}.",
  "sr.leftover": "Leftover {pct} of the pulls{dir}.",
  "sr.toSun": ", pointing toward the Sun",
  "sr.fromSun": ", pointing away from the Sun",
  "sr.percent": ({ n }) => `${n} percent`,
  "sr.tiny": "less than 0.01 percent",

  // ---- help dialog -----------------------------------------------------------------
  "help.title": "How to read this",
  "help.p1":
    'The view spins with the Sun and Earth, so both stand still. A probe that sits still in this spinning view feels three things: the <b class="c-sun">Sun\'s pull</b>, <b class="c-earth">Earth\'s pull</b>, and the <b class="c-spin">spin push</b> (the centrifugal effect of riding along), always pointing straight away from the centre of mass (CM).',
  "help.p2":
    "The arrows are drawn tip to tail. The <b>white leftover</b> runs from the probe to the end of the chain. When the chain closes back on the probe, nothing is left over: the probe can ride along with Earth, engine off. That spot is a Lagrange point.",
  "help.p3":
    "Arrows use the frame's natural scale, where the spin push is an exact copy of the dashed line from the CM to the probe. So balance means one thing you can see: <b>gravity lands on the target ring at the CM</b>. When arrows would get too long they all shrink together, and the target slides along the dashed line by the same factor.",
  "help.p4":
    '"Sun" and "Earth" are just names for a heavier and a lighter body. The default mass (25% of the Sun) is exaggerated so every effect is easy to see; the Earth tick on the slider is the real ratio.',
  "help.keys": "Keys",
  "help.kMove": "Move the probe (Shift: faster, Alt: finer)",
  "help.kJump": "Jump to L1–L5 (once found)",
  "help.kMass": "Change the mass (Shift: next preset)",
  "help.kSweep": "Sweep the mass",
  "help.kSpace": "Let go / catch the probe (chapters “Let go” and “Explore”)",
  "help.kFan": "Chain or fan arrows",
  "help.kZoom": "Zoom to Earth / fit view (+ and − zoom)",
  "help.kReset": "Reset probe and mass",
  "help.kChapter": "Previous / next chapter",
  "help.kEsc": "Stop an animation, close this",
  "help.pointer": "Mouse and touch",
  "help.p5":
    "Press or tap anywhere to put the probe there, then drag. On touch screens the drag is relative, like a trackpad, so your finger never covers the arrows. Scroll or pinch to zoom; Shift-drag to pan. Hold Alt to turn off snapping.",
  "help.close": "Close help",

  // ---- chapter 1: find ---------------------------------------------------------------
  "payoff.L1": "Earth's pull plus the spin push exactly cancel the Sun's pull.",
  "payoff.L2": "Out here the spin push beats the Sun's pull; Earth's pull makes up the difference.",
  "payoff.L3": "Behind the Sun: its pull plus Earth's small tug match the spin push.",
  "payoff.L4": "Gravity lands exactly on the centre of mass.",
  "payoff.L5": "The mirror of L4. Same triangle.",
  "find.demo": 'Three pulls act on the probe. <span class="muted">White = what is left over.</span>',
  "find.yourTurn": "Your turn: drag the probe until the white arrow vanishes.",
  "find.yourTurnTouch": "Your turn: drag anywhere to steer the probe until the white arrow vanishes.",
  "find.left": ({ n }) => `${n} left.`,
  "find.threeOnLine": "Three hide on the Sun–Earth line.",
  "find.allThreeOnLine": "All three are on the Sun–Earth line.",
  "find.mixed": ({ axis, off }) =>
    `${axis === 1 ? "One more" : `${axis} more`} on the Sun–Earth line, and ${off === 1 ? "one" : "two"} off it.`,
  "find.lastOnLine": "The last one is on the Sun–Earth line.",
  "find.restOnLine": "They are on the Sun–Earth line.",
  "find.mirror": "The mirror image of the one you found.",
  "find.twoOff": "Two hide off the line, equally far from the Sun and Earth.",
  "find.finale": "All five found. At every one the loop closes: nothing left over.",
  "chip.why": "Why a triangle? →",
  "chip.line": "Three on the line",
  "chip.letgo": "Let go",
  "find.predict":
    'Balanced: gravity lands exactly on the centre of mass. <span class="muted">Make Earth lighter or heavier. Does {name} move?</span>',
  "find.moves": "It moves",
  "find.stays": "It stays",
  "find.watch": "Watch the loop while Earth goes from its real mass to as heavy as the Sun.",
  "find.cmTag": "centre of mass",
  "find.landsTag": "lands on the CM",
  "find.result": "It stays. Any masses, same triangle.",
  "find.guessMoves": ' <span class="muted">You guessed “moves”. Most people do.</span>',
  "find.stopped": "Sweep stopped. Press ▶ to watch it again.",
  "chip.whyShort": "Why? →",
  "chip.keepHunting": "Keep hunting",
  "hint.line": "Hint: try the line through the Sun and Earth.",
  "hint.shrink": "Hint: keep shrinking the white arrow.",
  "hint.midline": "Hint: stand equally far from the Sun and Earth.",
  "hint.stuck": '{progress} <span class="muted">Stuck?</span>',
  "chip.showOne": "Show me one",
  "chip.showAll": "Show all",
  "find.shown": 'That is {name}. {payoff} <span class="muted">Drag away and come back to feel it snap.</span>',
  "find.showAll": "Here they are. Drag onto any of them and watch the loop close.",
  "find.midlineLabel": "equally far from Sun and Earth",
  "find.announce": "Balanced at {name}. {n} of 5 found.",

  // ---- chapter 6: explore --------------------------------------------------------------
  "explore.caption":
    'Free play. Drag the probe, sweep the mass, {zoom} to zoom. <span class="muted">Everything is in the ⋯ menu.</span>',
  "explore.scroll": "scroll",
  "explore.pinch": "pinch",
  "chip.sweep": "Sweep",
  "chip.zoomEarth": "Zoom to Earth",
};

const ru = {
  "page.title": "Точки Лагранжа",
  "page.question": "Где космический аппарат может лететь вместе с Землёй с выключенным двигателем?",
  "page.canvas":
    "Солнце, Земля и подвижный зонд. Стрелки показывают притяжение Солнца, притяжение Земли и центробежную силу вращающейся системы, выложенные одна за другой. Двигайте зонд клавишами со стрелками.",
  "page.noscript": "Для рисования сцены нужен JavaScript.",
  "page.lang": "English",
  "page.langShort": "EN",
  "page.langAria": "Переключить сайт на английский",

  "hud.tracker": "Найденные точки равновесия",
  "hud.showAll": "Показать все",
  "hud.help": "Справка и клавиши",
  "hud.menu": "Меню",
  "hud.legend": "Обозначения стрелок",
  "hud.hold": "Удерживать: реальное движение",
  "hud.holdTitle": "Удерживайте, чтобы увидеть настоящее движение без вращения вида",
  "slot.found": "{name}: найдена. Перейти",
  "slot.shown": "{name}: показана. Перейти",
  "slot.hidden": "{name}: ещё не найдена",
  "status.balanced": "Равновесие",
  "status.leftover": "Остаток {pct}",

  "leg.sun": "притяжение Солнца",
  "leg.earth": "притяжение Земли",
  "leg.cf": "центробежная",
  "leg.net": "остаток",
  "note.sun": "Притяжение Солнца: гравитация к Солнцу. Вдвое дальше — вчетверо слабее.",
  "note.earth": "Притяжение Земли: гравитация к Земле. То же правило, но Земля легче.",
  "note.cf":
    "Центробежная сила: вид вращается вместе с Солнцем и Землёй. Всё, что движется вместе с ними, отбрасывает прямо от центра масс (ЦМ), и тем сильнее, чем дальше. Пунктир — как у линии, которую она повторяет.",
  "note.net":
    "Остаток: три силы, сложенные одна за другой. Там, где он исчезает, зонд может лететь вместе с Землёй с выключенным двигателем.",

  "body.sun": "Солнце",
  "body.earth": "Земля",
  "body.cm": "ЦМ",
  "badge.scale": "стрелки ×{k}",
  "badge.lanes": "дорожки разведены для наглядности",
  "leftover.tiny": "< 0,01 %",

  "numbers.title": "Числа",
  "numbers.close": "Закрыть числа",
  "numbers.dSun": "До Солнца",
  "numbers.dEarth": "До Земли",
  "numbers.dCm": "До ЦМ",
  "numbers.leftover": "Остаток",
  "numbers.nearest": "Ближайшая точка",
  "numbers.hill": "Радиус Хилла",
  "numbers.footReal": "Реальное отношение Солнце–Земля: расстояния в км (1 a = 149,6 млн км).",
  "numbers.foot": "a — расстояние Солнце–Земля. Силы — в долях от суммы всех трёх.",
  "unit.km": "{n} км",
  "unit.mkm": "{n} млн км",

  "dock.label": "Подсказки и масса",
  "dock.chapters": "Главы",
  "dock.chapter": "Глава: {title}",
  "dock.sweep": "Прогнать массу от крошечной до равной и обратно",
  "dock.sweepTitle": "Прогнать массу (S)",
  "dock.stopSweep": "Остановить прогон",
  "dock.mass": "Масса Земли, % от Солнца",
  "mass.valuePreset": "{pct} массы Солнца, как в паре {system}",
  "mass.valueTag": "{pct} массы Солнца, {tag}",
  "tick.routhTitle": "Ниже примерно 4 % зонд в L4 или L5 после толчка остаётся рядом (предел Рауса)",
  "tick.routhAria": "Предел устойчивости, 4 процента",
  "tick.presetTitle": "Отношение масс {system}: {pct}",
  "tick.equalTitle": "Равные массы: {pct}",
  "tick.defaultTitle": "{pct}: значение сайта по умолчанию, нарочно преувеличено, чтобы все эффекты было легко увидеть",
  "tick.presetAria": "{label}: отношение {system}",

  "preset.earth": "Земля",
  "preset.earthShort": "Земля",
  "preset.jupiter": "Юпитер",
  "preset.jupiterShort": "Юп.",
  "preset.moon": "Луна",
  "preset.moonShort": "Луна",
  "preset.charon": "Харон",
  "preset.charonShort": "Харон",
  "system.earth": "Солнце–Земля",
  "system.jupiter": "Солнце–Юпитер",
  "system.moon": "Земля–Луна",
  "system.charon": "Плутон–Харон",
  "system.default": "значение по умолчанию",
  "system.equal": "равные массы",
  "tag.system": "как у пары {system}",
  "tag.equal": "равные массы",
  "tag.lighter": "в {x} раз легче реальной Земли",
  "tag.real": "почти как реальная Земля",
  "tag.heavier": "{x}× реальной Земли",
  "num.million": "{n} млн",

  "chapter.find": "Найдите равновесие",
  "chapter.triangle": "Почему треугольник?",
  "chapter.line": "Три на линии",
  "chapter.real": "Реальный масштаб",
  "chapter.letgo": "Отпустить",
  "chapter.explore": "Свободный режим",

  "menu.layers": "Слои",
  "menu.numbers": "Числа",
  "menu.real": "Удерживать: реальное движение",
  "menu.showAll": "Показать все точки",
  "menu.share": "Скопировать ссылку на этот вид",
  "menu.reset": "Сбросить зонд и массу",
  "menu.restart": "Начать заново",
  "menu.help": "Справка и клавиши",
  "layer.labels": "Подписи стрелок",
  "layer.sight": "Линии к Солнцу, Земле и ЦМ",
  "layer.magnifier": "Увеличивать крошечный остаток",
  "layer.compass": "Окружности радиуса a",
  "layer.shares": "Доли масс",
  "layer.profile": "Сила вдоль оси",
  "layer.fan": "Стрелки веером (не цепочкой)",
  "layer.locked": "Скрыто во время поиска: это подсказка к ответу",
  "ui.fit": "Весь вид",
  "ui.close": "Закрыть",
  "toast.notFound": "Ещё не найдена. Ищите!",
  "toast.copied": "Ссылка скопирована",
  "announce.notFound": "{name} ещё не найдена.",
  "confirm.restart": "Начать заново? Найденные точки будут забыты.",

  "sr.balanced": "Равновесие в {name}.",
  "sr.leftover": "Остаток — {pct} от суммы сил{dir}.",
  "sr.toSun": ", направлен к Солнцу",
  "sr.fromSun": ", направлен от Солнца",
  "sr.percent": ({ value }) =>
    plural(value, { one: "{n} процент", few: "{n} процента", many: "{n} процентов", other: "{n} процента" }),
  "sr.tiny": "меньше 0,01 процента",

  "help.title": "Как это читать",
  "help.p1":
    'Вид вращается вместе с Солнцем и Землёй, поэтому они стоят на месте. Зонд, неподвижный в этом вращающемся виде, чувствует три силы: <b class="c-sun">притяжение Солнца</b>, <b class="c-earth">притяжение Земли</b> и <b class="c-spin">центробежную силу</b> (эффект вращения вместе с системой), которая всегда направлена прямо от центра масс (ЦМ).',
  "help.p2":
    "Стрелки выложены одна за другой. <b>Белый остаток</b> идёт от зонда к концу цепочки. Когда цепочка замыкается на зонде, ничего не остаётся: зонд может лететь вместе с Землёй с выключенным двигателем. Это и есть точка Лагранжа.",
  "help.p3":
    "Стрелки нарисованы в естественном масштабе вращающейся системы, где центробежная сила — точная копия пунктира от ЦМ к зонду. Поэтому равновесие видно сразу: <b>притяжение приходит в кольцо-мишень в ЦМ</b>. Если стрелки становятся слишком длинными, все они уменьшаются вместе, а мишень сдвигается вдоль пунктира во столько же раз.",
  "help.p4":
    "«Солнце» и «Земля» — просто имена для тяжёлого и лёгкого тела. Масса по умолчанию (25 % массы Солнца) нарочно преувеличена, чтобы все эффекты было легко увидеть; отметка «Земля» на ползунке — реальное отношение.",
  "help.keys": "Клавиши",
  "help.kMove": "Двигать зонд (Shift — быстрее, Alt — точнее)",
  "help.kJump": "Перейти к L1–L5 (когда найдены)",
  "help.kMass": "Менять массу (Shift — следующая отметка)",
  "help.kSweep": "Прогнать массу",
  "help.kSpace": "Отпустить / поймать зонд (главы «Отпустить» и «Свободный режим»)",
  "help.kFan": "Цепочка или веер стрелок",
  "help.kZoom": "К Земле / весь вид (+ и − — масштаб)",
  "help.kReset": "Сбросить зонд и массу",
  "help.kChapter": "Предыдущая / следующая глава",
  "help.kEsc": "Остановить анимацию, закрыть это окно",
  "help.pointer": "Мышь и касание",
  "help.p5":
    "Нажмите или коснитесь любого места, чтобы поставить туда зонд, и тяните. На сенсорных экранах движение относительное, как на тачпаде, поэтому палец не закрывает стрелки. Прокрутка или щипок — масштаб; Shift и перетаскивание — сдвиг вида. Удерживайте Alt, чтобы отключить притягивание к точкам.",
  "help.close": "Закрыть справку",

  "payoff.L1": "Притяжение Земли и центробежная сила точно уравновешивают притяжение Солнца.",
  "payoff.L2": "Здесь центробежная сила больше притяжения Солнца; притяжение Земли восполняет разницу.",
  "payoff.L3": "За Солнцем: его притяжение плюс слабое притяжение Земли уравновешивают центробежную силу.",
  "payoff.L4": "Притяжение приходит точно в центр масс.",
  "payoff.L5": "Зеркальное отражение L4. Тот же треугольник.",
  "find.demo": 'На зонд действуют три силы. <span class="muted">Белая стрелка — то, что остаётся.</span>',
  "find.yourTurn": "Ваша очередь: тяните зонд, пока белая стрелка не исчезнет.",
  "find.yourTurnTouch": "Ваша очередь: ведите пальцем в любом месте экрана, пока белая стрелка не исчезнет.",
  "find.left": ({ n }) => `Осталось найти: ${n}.`,
  "find.threeOnLine": "Три прячутся на линии Солнце–Земля.",
  "find.allThreeOnLine": "Все три — на линии Солнце–Земля.",
  "find.mixed": ({ axis, off }) =>
    `Ещё ${axis === 1 ? "одна" : axis === 2 ? "две" : axis} на линии Солнце–Земля и ${off === 1 ? "одна" : "две"} вне её.`,
  "find.lastOnLine": "Последняя — на линии Солнце–Земля.",
  "find.restOnLine": "Они на линии Солнце–Земля.",
  "find.mirror": "Зеркальное отражение той, что вы нашли.",
  "find.twoOff": "Две прячутся вне линии, на равном расстоянии от Солнца и Земли.",
  "find.finale": "Все пять найдены. В каждой петля замыкается: ничего не остаётся.",
  "chip.why": "Почему треугольник? →",
  "chip.line": "Три на линии",
  "chip.letgo": "Отпустить",
  "find.predict":
    'Равновесие: притяжение приходит точно в центр масс. <span class="muted">Сделайте Землю легче или тяжелее. Сдвинется ли {name}?</span>',
  "find.moves": "Сдвинется",
  "find.stays": "Останется",
  "find.watch": "Следите за петлёй, пока Земля тяжелеет от реальной массы до массы Солнца.",
  "find.cmTag": "центр масс",
  "find.landsTag": "попадает в ЦМ",
  "find.result": "Не сдвинулась. Любые массы — тот же треугольник.",
  "find.guessMoves": ' <span class="muted">Вы думали, что сдвинется. Так думает большинство.</span>',
  "find.stopped": "Прогон остановлен. Нажмите ▶, чтобы посмотреть снова.",
  "chip.whyShort": "Почему? →",
  "chip.keepHunting": "Искать дальше",
  "hint.line": "Подсказка: попробуйте на линии через Солнце и Землю.",
  "hint.shrink": "Подсказка: продолжайте укорачивать белую стрелку.",
  "hint.midline": "Подсказка: встаньте на равном расстоянии от Солнца и Земли.",
  "hint.stuck": '{progress} <span class="muted">Застряли?</span>',
  "chip.showOne": "Покажите одну",
  "chip.showAll": "Показать все",
  "find.shown": 'Это {name}. {payoff} <span class="muted">Отведите зонд и вернитесь — почувствуйте, как он защёлкнется.</span>',
  "find.showAll": "Вот они. Наведите зонд на любую и смотрите, как замыкается петля.",
  "find.midlineLabel": "на равном расстоянии от Солнца и Земли",
  "find.announce": "Равновесие в {name}. Найдено {n} из 5.",

  "explore.caption":
    'Свободный режим. Двигайте зонд, прогоняйте массу, {zoom} — масштаб. <span class="muted">Остальное — в меню ⋯.</span>',
  "explore.scroll": "прокрутка",
  "explore.pinch": "щипок",
  "chip.sweep": "Прогнать массу",
  "chip.zoomEarth": "К Земле",
};

export const t = defineStrings({ en, ru });
